modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="gsu"
version="1.0.0"
displayName="Grape's Shut Up"
description='''
A mod that completely removes items, blocks, entities, and structures from the game based on a configuration file.
'''
authors="Grape"
credits=""
logoFile=""
updateJSONURL=""
displayURL=""
issueTrackerURL=""

[[dependencies.gsu]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.gsu]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"